liip_imagine:
    driver: "gd" # You can use "imagick" if you have it installed
    resolvers:
        default:
            web_path: ~

    twig:
        mode: lazy
    filter_sets:
        cache: ~

        thumbnail:
            quality: 85
            filters:
                thumbnail: { size: [100, 100], mode: outbound }
        
        medium:
            quality: 85
            filters:
                thumbnail: { size: [350, 200], mode: outbound }
        
        large:
            quality: 90
            filters:
                thumbnail: { size: [800, 600], mode: outbound }