liip_imagine:
    driver: "gd" # You can use "imagick" if you have it installed
    
    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: 'media/cache'
    twig:
        mode: lazy

    filter_sets:
        cache: ~
        
        # Filters used in templates
        thumbnail:
            quality: 85
            filters:
                thumbnail: { size: [100, 100], mode: outbound }
        
        medium:
            quality: 85
            filters:
                thumbnail: { size: [300, 300], mode: outbound }
        
        large:
            quality: 90
            filters:
                thumbnail: { size: [800, 600], mode: outbound }