vich_uploader:
    db_driver: orm
    mappings:
        news_images:
            uri_prefix: /uploads/news
            upload_destination: '%kernel.project_dir%/public/uploads/news'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true